### ISSUE TITLE
Remove the black color for highlighted text in source panel?

### ISSUE THREAD

**Issue by stpn** [mauricecruz/zero-base-themes#55]
Hi, how would I modify the styles to keep original text color for

```css
     .CodeMirror .CodeMirror-selectedtext:not(.CodeMirror-persist-highlight)
```
?

Currently it is set to highlight all the text in black.

**Comment by mauricecruz** [comment]
@stpn Can you give me a bit more context on which panel/view you're referring to and perhaps a screenshot? I assume you mean the sources panel, but I just want to be clear. 

If you are referring to the sources panel, the issue lies with devtools css itself. They're inlining the selector with the `!important` property via javascript. 

I'll file a bug/feature request with them to see if they can improve it.

**Comment by mauricecruz** [comment]
@stpn are you still having issues? If so, please post a screenshot and chrome version .

**Comment by mauricecruz** [comment]
Please open another issue if this is still a problem.
