### ISSUE TITLE
Dark theme included in Chrome 51 without this extension

### ISSUE THREAD

**Issue by therealmarv** [mauricecruz/zero-base-themes#69]
Don't get me wrong. I love this extension but maybe you should at least mention that Chrome itself has now a dark theme 😢😌

I can use it without any flag switches in my Chrome 51 and it also works in React developer tools

http://thenextweb.com/insider/2016/02/10/google-chromes-developer-tools-are-finally-getting-a-dark-theme/
https://developers.google.com/web/updates/2016/02/devtools-digest-devtools-go-dark

**Comment by mauricecruz** [comment]
😉 . I do mention it in my twitter - https://twitter.com/_mauricecruz/status/705307385645109248. 

The scope of zero base themes is a bit different though since this lets you load alternative themes other than the default dark theme. 

It just so happens that chrome's native dark theme is very similar looking to zero dark matrix. Maybe I'll put a footnote in that repo.

Thanks for the tip!

**Comment by s10wen** [comment]
@mauricecruz done :)

**Comment by mauricecruz** [comment]
👏  👏 👏

Thanks @s10wen!
